name: flutter_poc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  linkwell: ^2.0.6
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  flutter_overboard: ^3.1.3
  # firebase plugins
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  firebase_storage: ^11.6.11
  firebase_crashlytics: ^3.4.20
  firebase_analytics: ^10.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design:
    true

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/lottie/
    - assets/images/
    - assets/images/app_icon/

  # To add custom fonts to your application, add a fonts section here,
  # fonts:
  #   - family: Spezia
  #     fonts:
  #       - asset: assets/fonts/spezia/Spezia-Regular.otf
  #       - asset: assets/fonts/spezia/Spezia-RegularItalic.otf
  #       - asset: assets/fonts/spezia/Spezia-WideMedium.otf
  #       - asset: assets/fonts/spezia/Spezia-WideMediumItalic.otf
  #         style: normal
  #         weight: 400
