// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBcIJxhpvCLtPMyVynnCXyQN6m0gljPYk',
    appId: '1:976302128491:web:1f764d67d3c94e09faa02e',
    messagingSenderId: '976302128491',
    projectId: 'flutter-poc-390fb',
    authDomain: 'flutter-poc-390fb.firebaseapp.com',
    storageBucket: 'flutter-poc-390fb.appspot.com',
    measurementId: 'G-MYEPV8EVWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsBf4YQBfY2mKR91nE1x-3IPHc7TfLPrE',
    appId: '1:976302128491:android:773c38ba52202bc3faa02e',
    messagingSenderId: '976302128491',
    projectId: 'flutter-poc-390fb',
    storageBucket: 'flutter-poc-390fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA149yEJ1eVPGK308ugEwTddXFVsip5XWY',
    appId: '1:976302128491:ios:3ec78d4b55970f04faa02e',
    messagingSenderId: '976302128491',
    projectId: 'flutter-poc-390fb',
    storageBucket: 'flutter-poc-390fb.appspot.com',
    iosBundleId: 'com.example.flutterPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA149yEJ1eVPGK308ugEwTddXFVsip5XWY',
    appId: '1:976302128491:ios:aa1e35c862dc1554faa02e',
    messagingSenderId: '976302128491',
    projectId: 'flutter-poc-390fb',
    storageBucket: 'flutter-poc-390fb.appspot.com',
    iosBundleId: 'com.example.flutterPoc.RunnerTests',
  );
}
